# Generated by Django 4.2.29 on 2026-03-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0002_communityreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastereport',
            name='quantity_kg',
        ),
    ]
