# Generated by Django 4.2.29 on 2026-03-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0003_remove_wastereport_quantity_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangayprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
