# Generated by Django 4.2.29 on 2026-03-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0004_barangayprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='emoji',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='collectionschedule',
            name='waste_category',
            field=models.CharField(choices=[('biodegradable', 'Biodegradable'), ('recyclable', 'Recyclable'), ('residual', 'Residual'), ('special', 'Special Waste'), ('hazardous', 'Hazardous'), ('electronic', 'E-Waste')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='category',
            field=models.CharField(choices=[('biodegradable', 'Biodegradable'), ('recyclable', 'Recyclable'), ('residual', 'Residual'), ('special', 'Special Waste'), ('hazardous', 'Hazardous'), ('electronic', 'E-Waste')], max_length=50),
        ),
    ]
