# Generated by Django 4.2.29 on 2026-04-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0006_announcement_send_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='verification_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='verification_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('report', 'Report Update'), ('level_up', 'Level Up'), ('collection', 'Collection Reminder'), ('system', 'System')], default='announcement', max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='waste_manag_user_id_ca7591_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='waste_manag_created_ad92d5_idx'),
        ),
        migrations.AddIndex(
            model_name='wastereport',
            index=models.Index(fields=['image_hash'], name='waste_manag_image_h_b399f6_idx'),
        ),
        migrations.AddIndex(
            model_name='wastereport',
            index=models.Index(fields=['verification_passed'], name='waste_manag_verific_7cd3a4_idx'),
        ),
        migrations.AddIndex(
            model_name='wastereport',
            index=models.Index(fields=['status', 'reported_at'], name='waste_manag_status_90068a_idx'),
        ),
    ]
