# Generated by Django 4.2.29 on 2026-04-04 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste_management', '0007_wastereport_address_wastereport_image_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityreply',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityreply',
            name='parent_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='waste_management.communityreply'),
        ),
    ]
