# Generated by Django 4.2.29 on 2026-04-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0010_alter_userfollow_follower_alter_userfollow_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangayprofile',
            name='allow_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='barangayprofile',
            name='is_profile_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='barangayprofile',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='barangayprofile',
            name='show_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='barangayprofile',
            name='show_location',
            field=models.BooleanField(default=True),
        ),
    ]
