# Generated by Django 4.2.29 on 2026-04-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0014_communitypost_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='community/videos/'),
        ),
    ]
