# Generated by Django 4.2.29 on 2026-04-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0015_fix_video_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangayprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='barangayprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
