# Generated by Django 4.2.29 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0016_barangayprofile_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('announcement', 'Announcement'),
                    ('report', 'Report Update'),
                    ('level_up', 'Level Up'),
                    ('collection', 'Collection Reminder'),
                    ('system', 'System'),
                    ('like', 'Post Liked'),
                    ('reply', 'New Reply'),
                    ('share', 'Post Shared'),
                    ('mention', 'Mentioned'),
                    ('tag', 'Tagged in Post'),
                    ('registration', 'New Registration'),
                ],
                default='announcement',
                max_length=50,
            ),
        ),
    ]