# Generated by Django 4.2.29 on 2026-04-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0017_add_notification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes visible to the user', null=True),
        ),
    ]
