# Generated by Django 4.2.29 on 2026-04-16 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0018_wastereport_admin_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('purok', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('reporter_id', models.IntegerField(blank=True, null=True)),
                ('reporter_username', models.CharField(blank=True, max_length=150, null=True)),
                ('reporter_full_name', models.CharField(blank=True, max_length=300, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by_id', models.IntegerField(blank=True, null=True)),
                ('deleted_by_username', models.CharField(blank=True, max_length=150, null=True)),
                ('deleted_by_role', models.CharField(default='user', max_length=10)),
            ],
            options={
                'db_table': 'waste_management_deletedreport',
                'ordering': ['-deleted_at'],
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='wastereport',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_reports', to='waste_management.wastereport'),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='is_duplicate',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
