# Generated by Django 4.2.29 on 2026-04-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0019_deletedreport_wastereport_duplicate_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
