# Generated by Django 4.2.29 on 2026-04-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0020_wastereport_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
