# Generated by Django 4.2.29 on 2026-04-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0021_wastereport_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
