# Generated by Django 4.2.29 on 2026-04-18 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste_management', '0022_wastereport_is_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('duplicate', 'Duplicate Report'), ('suspicious', 'Suspicious / Unverified'), ('spam', 'Spam / Irrelevant'), ('incomplete', 'Incomplete Information'), ('invalid_location', 'Invalid Location'), ('invalid_image', 'Blurry / Invalid Image'), ('wrong_category', 'Wrong Category'), ('false_report', 'False Report (Confirmed)'), ('abusive', 'Abusive / Inappropriate Content')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flagged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_reports', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='waste_management.wastereport')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report', 'flag_type'], name='waste_manag_report__454358_idx'), models.Index(fields=['created_at'], name='waste_manag_created_4dc6c7_idx')],
            },
        ),
    ]
