# Generated by Django 4.2.29 on 2026-04-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0023_reportflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='admin_notes_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
