# Generated by Django 4.2.29 on 2026-04-24 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste_management', '0024_wastereport_admin_notes_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender', models.CharField(choices=[('ai', 'AI Bot'), ('user', 'User'), ('admin', 'Admin')], default='ai', max_length=10)),
                ('status', models.CharField(choices=[('ai_only', 'AI Only'), ('pending_human', 'Pending Human Admin'), ('human_active', 'Human Admin Active'), ('closed', 'Closed')], default='ai_only', max_length=15)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('admin_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='waste_management.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='waste_manag_user_id_ad59e4_idx'), models.Index(fields=['created_at'], name='waste_manag_created_ca789c_idx'), models.Index(fields=['is_read'], name='waste_manag_is_read_320568_idx')],
            },
        ),
    ]
