# Generated by Django 4.2.29 on 2026-04-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0025_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangayprofile',
            name='chat_mode',
            field=models.CharField(choices=[('ai', 'AI Mode'), ('human', 'Human Mode')], default='ai', max_length=10),
        ),
        migrations.AddField(
            model_name='barangayprofile',
            name='chat_session_active',
            field=models.BooleanField(default=False),
        ),
    ]
